export const CLINICAL_ROLES = [
  "Physician",
  "Medical Student",
  "Fellow",
  "Nurse",
  "Pharmacist",
  "Resident",
  "Coder (RCM, ICD, CPT)",
  "Other",
];

export const TRAINING_SPECIALTIES = [
  "Anesthesiology",
  "Cardiology",
  "Certified Medical/Insurance Coder (RCM, ICD, CPT)",
  "Dentistry",
  "Dermatology",
  "Emergency Medicine",
  "Family Medicine",
  "Gastroenterology",
  "General Surgery",
  "Internal Medicine",
  "Neurology",
  "Ob/Gyn",
  "Oncology",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Pathology",
  "Pediatrics",
  "Psychiatry",
  "Pulmonology",
  "Radiology",
  "Urology",
  "Vascular Surgery",
  "Veterinary",
  "Other",
];


export const REFERRAL_SOURCES = [
  { value: "linkedin", label: "LinkedIn" },
  { value: "indeed", label: "Indeed" },
  { value: "friend-colleague", label: "Friend or colleague" },
  { value: "job-board", label: "Job board" },
  { value: "google", label: "Google" },
  { value: "other", label: "Other" },
];

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "India",
  "Germany",
  "France",
  "Brazil",
  "Mexico",
  "Netherlands",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Poland",
  "Czech Republic",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Saudi Arabia",
  "United Arab Emirates",
  "Israel",
  "Turkey",
  "Japan",
  "South Korea",
  "China",
  "Singapore",
  "Malaysia",
  "Philippines",
  "Indonesia",
  "Thailand",
  "New Zealand",
  "Argentina",
  "Colombia",
  "Chile",
  "Other",
];
