export const CLINICAL_ROLES = [
  "Physician",
  "Resident",
  "Fellow",
  "Medical Student",
  "Nurse",
  "Nurse Practitioner (NP)",
  "Physician Assistant (PA)",
  "Lab Assistant",
  "Radiographer",
  "Billing Specialist",
  "Healthcare Administrator",
  "Other",
];

export const TRAINING_SPECIALTIES = [
  "Cardiology",
  "Dermatology",
  "Dentistry",
  "Emergency Medicine",
  "Endocrinology",
  "Gastroenterology",
  "General Medicine",
  "Hematology",
  "Infectious Disease",
  "Nephrology",
  "Neurology",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Pathology",
  "Pediatrics",
  "Psychiatry",
  "Pulmonology",
  "Radiology",
  "Rheumatology",
  "Surgery",
  "Urology",
  "Other",
];

export const YEARS_OF_EXPERIENCE = [
  { value: "less-than-2", label: "Less than 2 years" },
  { value: "3-5", label: "3–5 years" },
  { value: "6-10", label: "6–10 years" },
  { value: "10+", label: "10+ years" },
];

export const PORTAL_EXPERIENCE_OPTIONS = [
  { value: "first-time", label: "No, this is my first time" },
  { value: "completed-tasks", label: "Yes, I've completed tasks before" },
  { value: "referred", label: "Referred by a Centaur team member" },
];

export const REFERRAL_SOURCES = [
  { value: "linkedin", label: "LinkedIn" },
  { value: "indeed", label: "Indeed" },
  { value: "friend-colleague", label: "Friend or colleague" },
  { value: "job-board", label: "Job board" },
  { value: "google", label: "Google" },
  { value: "other", label: "Other" },
];

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "India",
  "Germany",
  "France",
  "Brazil",
  "Mexico",
  "Netherlands",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Poland",
  "Czech Republic",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Saudi Arabia",
  "United Arab Emirates",
  "Israel",
  "Turkey",
  "Japan",
  "South Korea",
  "China",
  "Singapore",
  "Malaysia",
  "Philippines",
  "Indonesia",
  "Thailand",
  "New Zealand",
  "Argentina",
  "Colombia",
  "Chile",
  "Other",
];
